# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       usbutils

# >> macros
# << macros

Summary:    Linux USB utilities
Version:    007
Release:    1
Group:      Applications/System
License:    GPLv2+
URL:        http://www.linux-usb.org/
Source0:    http://www.kernel.org/pub/linux/utils/usb/usbutils/%{name}-%{version}.tar.xz
Source1:    usbutils-rpmlintrc
Source100:  usbutils.yaml
Source101:  usbutils-007.tar.sign
Patch0:     usbutils-006-hwdata.patch
Patch1:     usbutils-make-hwdata.patch
Patch2:     02-ccid-typo.patch
Patch3:     lsusb-t-segfault.patch
Requires:   hwdata
BuildRequires:  pkgconfig(libusb-1.0)
BuildRequires:  autoconf
BuildRequires:  libtool

%description
This package contains utilities for inspecting devices connected to a
USB bus.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.


%prep
%setup -q -n %{name}-%{version}

# usbutils-006-hwdata.patch
%patch0 -p1
# usbutils-make-hwdata.patch
%patch1 -p1
# 02-ccid-typo.patch
%patch2 -p1
# lsusb-t-segfault.patch
%patch3 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --sbindir=%{_sbindir} \
    --datadir=%{_datadir}/hwdata \
    --disable-usbids

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%{_mandir}/*/*
%{_bindir}/*
%doc AUTHORS COPYING ChangeLog NEWS README
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_datadir}/pkgconfig/usbutils.pc
# << files devel
