# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       usbutils
Summary:    Linux USB utilities
Version:    005
Release:    1
Group:      Applications/System
License:    GPLv2+
URL:        http://www.linux-usb.org/
Source0:    gregkh-usbutils-v005-0-g90d96a3.tar.gz
Source1:    usbhid-dump-1.3.tar.bz2
Source2:    usbutils-rpmlintrc
Source100:  usbutils.yaml
Patch0:     usbutils-003-hwdata.patch
Patch1:     usbutils-make-hwdata.patch
Requires:   hwdata
BuildRequires:  pkgconfig(libusb-1.0)
BuildRequires:  autoconf
BuildRequires:  libtool


%description
This package contains utilities for inspecting devices connected to a
USB bus.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
%description devel
Development files for %{name}



%prep
%setup -q -n gregkh-%{name}-1ea4ac9

# usbutils-003-hwdata.patch
%patch0 -p1
# usbutils-make-hwdata.patch
%patch1 -p1
# >> setup
tar -x --strip-components=1 -f %{SOURCE1} -C usbhid-dump
# << setup

%build
# >> build pre
autoreconf --install --symlink
# << build pre

%configure --disable-static \
    --sbindir=%{_sbindir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_mandir}/*/*
%{_bindir}/*
%doc AUTHORS COPYING ChangeLog NEWS README
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_datadir}/pkgconfig/usbutils.pc
# << files devel


